# Generated by Django 2.2.6 on 2019-11-08 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191108_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SD', 'Shipped'), ('PD', 'Pending'), ('OD', 'OutForDelivery'), ('PO', 'PaymentDone'), ('CT', 'Cart'), ('AP', 'Approved'), ('PL', 'PayLater'), ('DL', 'Delivered')], default='PD', max_length=2)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('NP', 'NotPaid'), ('OP', 'OnlinePayment'), ('CP', 'CashPayment'), ('QP', 'ChequePayment')], default='NP', max_length=2)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('cart', models.ManyToManyField(blank=True, related_name='product_cart', to='product.Cart')),
            ],
        ),
    ]
